# Generated by Django 3.1.7 on 2021-03-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlimitapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='drinker_id',
            new_name='drinker',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='drinker_id',
            new_name='drinker',
        ),
    ]
