# Generated by Django 3.1.7 on 2021-03-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlimitapi', '0002_auto_20210318_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinker',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drinker',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drinker',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
