# Generated by Django 3.1.7 on 2021-03-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlimitapi', '0004_auto_20210318_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdrink',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='eventdrink',
            old_name='event_id',
            new_name='event',
        ),
    ]
