# Generated by Django 3.1.7 on 2021-03-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlimitapi', '0005_auto_20210321_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdrink',
            name='time_drank',
            field=models.DateTimeField(),
        ),
    ]
