# Generated by Django 3.1.7 on 2021-03-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlimitapi', '0006_auto_20210321_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
