# Generated by Django 3.1.7 on 2021-03-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlimitapi', '0008_auto_20210323_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='departure',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
